In [1]:
test= "hello world"

In [2]:
print(test)

hello world


In [3]:
import numpy as np

In [22]:
a = np.array([[1,2,3],[2,3,4]])

In [23]:
a.shape

(2, 3)

In [24]:
a = np.exp(a)

In [25]:
print(a)

[[ 2.71828183  7.3890561  20.08553692]
 [ 7.3890561  20.08553692 54.59815003]]


In [26]:
a=a.T
print(a)

[[ 2.71828183  7.3890561 ]
 [ 7.3890561  20.08553692]
 [20.08553692 54.59815003]]


In [30]:
s = np.sum(a,axis=1,keepdims=True) # this sums the entire row or col if axis=1 then rowwise if axis=0 then col wise

In [31]:
s

array([[10.10733793],
       [27.47459302],
       [74.68368696]])

In [32]:
s.reshape(3,1)

array([[10.10733793],
       [27.47459302],
       [74.68368696]])

In [33]:
s.reshape(1,3)

array([[10.10733793, 27.47459302, 74.68368696]])

In [34]:
s = np.sum(s,axis=1,keepdims=True)
s

array([[10.10733793],
       [27.47459302],
       [74.68368696]])

In [37]:
#Broadcasting means that say if a matrix is a and 
#another matrix is b b is having dim {m,1} or {1,m} & a is haing dim {m,n}or {n,m} then 
# a+b will or a*b will or any op will work using brodcsating concpet which means it will create copy of b at runtime
# m time and will perform +,-,*,/ op successfully
    

In [48]:
a = np.array([[1,2,3],[2,4,5]]) 
b= np.array([0,0,0])
a = a*2
a

array([[ 2,  4,  6],
       [ 4,  8, 10]])